version: '3.8'

services:
  postgres:
    container_name: loaders-online-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: loaders-online-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data: